<?php

/**
 * @file
 * This module adds "view" permission to bundles.
 */

/**
 * Implements hook_help().
 */
function simple_content_access_help($path, $arg) {
  
}

/**
 * Implements hook_menu_alter().
 */
function simple_content_access_menu_alter(&$items) {
  
}

/**
 * Implements hook_permission().
 */
function simple_content_access_permission() {
  $permissions = array();
  
  foreach (entity_get_info() as $entity) {
    foreach($entity['bundles'] as $bundle_name => $bundle_info) {
      $permissions["view $bundle_name content"] = array(
        'title' => "View $bundle_name content",
        'description' => "Allow user to view $bundle_name content",
      );
    }
  }
  
  return $permissions;
}

